#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Parses TRX test result files and outputs test statistics
.DESCRIPTION
    Parses .trx files generated by dotnet test and extracts test statistics.
    Outputs results to GitHub environment variables for CI/CD workflows.
.PARAMETER SourcePath
    Path to search for .trx files (defaults to "./src")
.PARAMETER Debug
    Enable debug output for troubleshooting (defaults to $false)
#>

param(
    [Parameter(Mandatory = $false)]
    [string]$SourcePath = "./src",

    [Parameter(Mandatory = $false)]
    [switch]$Debug
)

function Get-AttributeValue {
    param($Node, $AttributeName)
    if ($Node.$AttributeName) { [int]$Node.$AttributeName } else { 0 }
}

# Initialize counters
$totalTests = 0
$passedTests = 0
$failedTests = 0
$skippedTests = 0
$executionTime = [TimeSpan]::Zero

# Find TRX files
$trxFiles = Get-ChildItem -Path $SourcePath -Filter "*.trx" -Recurse
Write-Output "Found $($trxFiles.Count) TRX files"

if ($trxFiles.Count -eq 0) {
    Write-Warning "No TRX files found in path: $SourcePath"
    exit 1
}

# Parse test output logs for skipped tests
$testOutputFiles = @()
if (Test-Path "test_output_windows.log") {
    $testOutputFiles += "test_output_windows.log"
}
if (Test-Path "test_output_unix.log") {
    $testOutputFiles += "test_output_unix.log"
}

$outputSkippedTests = 0
foreach ($outputFile in $testOutputFiles) {
    if (Test-Path $outputFile) {
        if ($Debug) { Write-Output "Parsing test output file: $outputFile" }
        $content = Get-Content $outputFile -Raw

        # Look for various patterns that indicate skipped tests
        $skippedPatterns = @(
            '(\d+)\s+test\(s\)\s+skipped',
            '(\d+)\s+skipped',
            'Skipped:\s+(\d+)',
            '(\d+)\s+test\(s\)\s+ignored',
            '(\d+)\s+ignored',
            'Ignored:\s+(\d+)'
        )

        foreach ($pattern in $skippedPatterns) {
            $matches = [regex]::Matches($content, $pattern, [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
            foreach ($match in $matches) {
                $skipCount = [int]$match.Groups[1].Value
                $outputSkippedTests += $skipCount
                if ($Debug) { Write-Output "Found $skipCount skipped tests using pattern: $pattern" }
            }
        }

        if ($Debug) {
            Write-Output "Sample from $($outputFile):"
            $lines = $content -split "`n"
            $relevantLines = $lines | Where-Object { $_ -match "(test|skip|ignore|pass|fail|total)" } | Select-Object -First 5
            foreach ($line in $relevantLines) {
                Write-Output "  $line"
            }
        }
    }
}

if ($Debug) { Write-Output "Found $outputSkippedTests skipped tests from command output" }

foreach ($file in $trxFiles) {
    try {
        [xml]$trx = Get-Content $file.FullName
        $namespace = @{ns = 'http://microsoft.com/schemas/VisualStudio/TeamTest/2010'}

        # Parse test summary
        $summary = Select-Xml -Xml $trx -XPath "//ns:ResultSummary/ns:Counters" -Namespace $namespace
        if ($summary) {
            $counters = $summary.Node

            if ($Debug) {
                Write-Output "Processing $($file.Name):"
                $counters.Attributes | ForEach-Object { Write-Output "  $($_.Name) = $($_.Value)" }
            }

            # Get counts with safe parsing
            $total = Get-AttributeValue $counters 'total'
            $passed = Get-AttributeValue $counters 'passed'
            $failed = Get-AttributeValue $counters 'failed'

            # Sum all skipped/non-executed test types
            $fileSkipped = (Get-AttributeValue $counters 'inconclusive') +
                          (Get-AttributeValue $counters 'notExecuted') +
                          (Get-AttributeValue $counters 'notRunnable') +
                          (Get-AttributeValue $counters 'timeout') +
                          (Get-AttributeValue $counters 'aborted') +
                          (Get-AttributeValue $counters 'skipped')

            $totalTests += $total
            $passedTests += $passed
            $failedTests += $failed
            $skippedTests += $fileSkipped

            if ($Debug) {
                Write-Output "  Results: Total=$total, Passed=$passed, Failed=$failed, Skipped=$fileSkipped"
            }
        }

        # Parse execution time
        $times = Select-Xml -Xml $trx -XPath "//ns:Times" -Namespace $namespace
        if ($times) {
            $start = [DateTime]$times.Node.start
            $finish = [DateTime]$times.Node.finish
            $executionTime = $executionTime.Add($finish - $start)
        }
    } catch {
        Write-Warning "Failed to parse TRX file: $($file.FullName). Error: $_"
    }
}

# Calculate pass rate
if ($totalTests -gt 0) {
    $passTestRate = "**$([math]::Round(($passedTests / $totalTests) * 100, 1))%** ($passedTests/$totalTests tests passed)"
} else {
    $passTestRate = "No tests found"
}

# Generate timestamp
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss UTC"

# Use command output skipped count if it's higher than TRX parsing
if ($outputSkippedTests -gt $skippedTests) {
    if ($Debug) { Write-Output "Using command output skipped count ($outputSkippedTests) instead of TRX count ($skippedTests)" }
    $skippedTests = $outputSkippedTests
}

if ($Debug) { Write-Output "Final counts: TRX Skipped: $($skippedTests - $outputSkippedTests), Output Skipped: $outputSkippedTests, Total Skipped: $skippedTests" }

# Output results
Write-Output "Test Results Summary:"
Write-Output "Total: $totalTests, Passed: $passedTests, Failed: $failedTests, Skipped: $skippedTests"
Write-Output "Pass Rate: $passTestRate"
Write-Output "Duration: $($executionTime.ToString('hh\:mm\:ss'))"

# Final validation check
if ($skippedTests -eq 0) {
    Write-Output ""
    Write-Output "WARNING: No skipped tests detected. This could mean:"
    Write-Output "1. Your test suite doesn't have any skipped tests ([Skip], [Ignore], etc.)"
    Write-Output "2. The TRX format is different than expected"
    Write-Output "3. Test conditions aren't being met that would cause skips"
    Write-Output ""
    Write-Output "To verify, try adding a test with [Skip] or [Ignore] attribute in your test suite."
}

# Output to GitHub environment variables
if ($env:GITHUB_ENV) {
    "TEST_TOTAL=$totalTests" | Out-File -FilePath $env:GITHUB_ENV -Append
    "TEST_PASSED=$passedTests" | Out-File -FilePath $env:GITHUB_ENV -Append
    "TEST_FAILED=$failedTests" | Out-File -FilePath $env:GITHUB_ENV -Append
    "TEST_SKIPPED=$skippedTests" | Out-File -FilePath $env:GITHUB_ENV -Append
    "PASS_TEST_RATE=$passTestRate" | Out-File -FilePath $env:GITHUB_ENV -Append
    "TEST_DURATION=$($executionTime.TotalSeconds)" | Out-File -FilePath $env:GITHUB_ENV -Append
    "LAST_UPDATED=$timestamp" | Out-File -FilePath $env:GITHUB_ENV -Append
}