#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Parses TRX test result files and outputs test statistics
.DESCRIPTION
    Parses .trx files generated by dotnet test and extracts test statistics.
    Outputs results to GitHub environment variables for CI/CD workflows.
.PARAMETER SourcePath
    Path to search for .trx files (defaults to "./src")
.PARAMETER EnableDebug
    Enable debug output for troubleshooting (defaults to $false)
#>

param(
    [Parameter(Mandatory = $false)]
    [string]$SourcePath = "./src",

    [Parameter(Mandatory = $false)]
    [switch]$EnableDebug
)

function Get-AttributeValue {
    param($Node, $AttributeName)
    if ($Node.$AttributeName) { [int]$Node.$AttributeName } else { 0 }
}

# Initialize counters
$totalTests = 0
$passedTests = 0
$failedTests = 0
$skippedTests = 0
$executionTime = [TimeSpan]::Zero
$frameworkVersions = @()

# Find TRX files
$trxFiles = Get-ChildItem -Path $SourcePath -Filter "*.trx" -Recurse
Write-Output "Found $($trxFiles.Count) TRX files"

if ($trxFiles.Count -eq 0) {
    Write-Warning "No TRX files found in path: $SourcePath"
    exit 1
}


foreach ($file in $trxFiles) {
    try {
        [xml]$trx = Get-Content $file.FullName
        $namespace = @{ns = 'http://microsoft.com/schemas/VisualStudio/TeamTest/2010'}

        # Parse test summary
        $summary = Select-Xml -Xml $trx -XPath "//ns:ResultSummary/ns:Counters" -Namespace $namespace
        if ($summary) {
            $counters = $summary.Node

            if ($EnableDebug) {
                Write-Output "Processing $($file.Name):"
                $counters.Attributes | ForEach-Object { Write-Output "  $($_.Name) = $($_.Value)" }
            }

            # Get counts with safe parsing
            $total = Get-AttributeValue $counters 'total'
            $passed = Get-AttributeValue $counters 'passed'
            $failed = Get-AttributeValue $counters 'failed'

            $totalTests += $total
            $passedTests += $passed
            $failedTests += $failed

            if ($EnableDebug) {
                Write-Output "  Results: Total=$total, Passed=$passed, Failed=$failed"
            }
        }

        # Parse execution time
        $times = Select-Xml -Xml $trx -XPath "//ns:Times" -Namespace $namespace
        if ($times) {
            $start = [DateTime]$times.Node.start
            $finish = [DateTime]$times.Node.finish
            $executionTime = $executionTime.Add($finish - $start)
        }

        # Extract framework version from test settings or deployment
        $testSettings = Select-Xml -Xml $trx -XPath "//ns:TestSettings" -Namespace $namespace
        if ($testSettings -and $testSettings.Node.deploymentRoot) {
            $deploymentPath = $testSettings.Node.deploymentRoot
            if ($deploymentPath -match '(net\d+\.\d+|netstandard\d+\.\d+|netframework\d+\.\d+|net\d+)') {
                $framework = $matches[1]
                if ($frameworkVersions -notcontains $framework) {
                    $frameworkVersions += $framework
                    if ($EnableDebug) {
                        Write-Output "  Found framework: $framework"
                    }
                }
            }
        }

        # Alternative: Extract from file path (for cases where deployment info isn't available)
        if ($file.FullName -match '(net\d+\.\d+|netstandard\d+\.\d+|netframework\d+\.\d+|net\d+)') {
            $framework = $matches[1]
            if ($frameworkVersions -notcontains $framework) {
                $frameworkVersions += $framework
                if ($EnableDebug) {
                    Write-Output "  Found framework from path: $framework"
                }
            }
        }
    } catch {
        Write-Warning "Failed to parse TRX file: $($file.FullName). Error: $_"
    }
}

# Calculate pass rate
if ($totalTests -gt 0) {
    $passTestRate = "**$([math]::Round(($passedTests / $totalTests) * 100, 1))%** ($passedTests/$totalTests tests passed)"
} else {
    $passTestRate = "No tests found"
}

# Generate timestamp
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss UTC"

# Calculate skipped tests using simple math
$skippedTests = $totalTests - $passedTests - $failedTests

if ($EnableDebug) { Write-Output "Calculated skipped tests: $totalTests - $passedTests - $failedTests = $skippedTests" }

# Format framework versions
$testedFrameworks = if ($frameworkVersions.Count -gt 0) {
    ($frameworkVersions | Sort-Object) -join ", "
} else {
    "Not detected"
}

# Output results
Write-Output "Test Results Summary:"
Write-Output "Total: $totalTests, Passed: $passedTests, Failed: $failedTests, Skipped: $skippedTests"
Write-Output "Pass Rate: $passTestRate"
Write-Output "Duration: $($executionTime.ToString('hh\:mm\:ss'))"
Write-Output "Frameworks Tested: $testedFrameworks"

# Final validation check
if ($skippedTests -eq 0) {
    Write-Output ""
    Write-Output "WARNING: No skipped tests detected. This could mean:"
    Write-Output "1. Your test suite doesn't have any skipped tests ([Skip], [Ignore], etc.)"
    Write-Output "2. The TRX format is different than expected"
    Write-Output "3. Test conditions aren't being met that would cause skips"
    Write-Output ""
    Write-Output "To verify, try adding a test with [Skip] or [Ignore] attribute in your test suite."
}

# Output to GitHub environment variables
if ($env:GITHUB_ENV) {
    "TEST_TOTAL=$totalTests" | Out-File -FilePath $env:GITHUB_ENV -Append
    "TEST_PASSED=$passedTests" | Out-File -FilePath $env:GITHUB_ENV -Append
    "TEST_FAILED=$failedTests" | Out-File -FilePath $env:GITHUB_ENV -Append
    "TEST_SKIPPED=$skippedTests" | Out-File -FilePath $env:GITHUB_ENV -Append
    "PASS_TEST_RATE=$passTestRate" | Out-File -FilePath $env:GITHUB_ENV -Append
    "TEST_DURATION=$($executionTime.TotalSeconds)" | Out-File -FilePath $env:GITHUB_ENV -Append
    "TESTED_FRAMEWORKS=$testedFrameworks" | Out-File -FilePath $env:GITHUB_ENV -Append
    "LAST_UPDATED=$timestamp" | Out-File -FilePath $env:GITHUB_ENV -Append
}