name: publish to github
on:
  workflow_dispatch:
jobs:
  publish:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/build_and_test_job.yaml
        with:
          os: ubuntu-latest
          dotnet_version: '6.0.x'
          hook_manager_type: MonoMod
      - name: Pack
        run: dotnet pack --no-build --configuration Release --output packages src/StaticMock/StaticMock.csproj
      - name: Prepare
        run: dotnet nuget add source --username SvetlovA --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/SvetlovA/index.json"
      - name: Push
        run: dotnet nuget push packages/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"
