name: publish
on:
  workflow_dispatch:
jobs:
  buildAndTest:
    uses: ./.github/workflows/build_and_test.yaml
  pack:
    needs: buildAndTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Pack
        run: dotnet pack --configuration Release --output packages src/StaticMock/StaticMock.csproj
      - uses: actions/upload-artifact@v5
        with:
          name: pack-drop
          path: packages/*.nupkg
  githubPublish:
      runs-on: ubuntu-latest
      needs: pack
      steps:
      - uses: actions/download-artifact@v6
        with:
          name: pack-drop
      - name: Prepare
        run: dotnet nuget add source --username SvetlovA --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/SvetlovA/index.json"
      - name: Push
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"
  nugetPublish:
      runs-on: ubuntu-latest
      needs: pack
      steps:
      - uses: actions/download-artifact@v6
        with:
          name: pack-drop
      - name: Push
        run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
